name: Neofetch
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1440
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies (Ubuntu 24.04 Pro)
        shell: bash
        run: |
          echo "Updating package lists..."
          sudo apt-get update
          
          echo "Installing required dependencies..."
          # Installing git-lfs, make, and OpenJDK 17 (JDK is recommended over JRE for build environments)
          sudo apt-get install -y neofetch
          neofetch
