name: Upload test (PixelDrain and GoFile)
on: workflow_dispatch
jobs:
  upload-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Test File
        run: echo "This is a test file for upload." > testfile.txt
        shell: bash        

      - name: Upload using Custom Action
        uses: ./.github/actions/gofile-upload
        with:
            filepath: 'testfile.txt'